name: kedro-feature-and-inference-pipelines

on:
  workflow_dispatch:  # Manual trigger

jobs:
  run_kedro_pipelines:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip uninstall -y kedro
          pip install -r requirements.txt

      - name: Run Kedro Feature Pipeline
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: kedro run --pipeline feature_pipeline

      - name: Run Kedro Inference Pipeline
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: kedro run --pipeline inference_pipeline

      - name: Commit and Push outputs
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Automated pipeline output pushed by GitHub Actions"
          branch: main
          commit_options: '--no-verify --signoff'
          file_pattern: |
            data/08_reporting/actual_iris.png
            data/08_reporting/latest_iris.png
            data/08_reporting/confusion_matrix.png
            data/08_reporting/history_predictions.xlsx
          repository: .
          commit_user_name: Kedro Bot
          commit_user_email: kedro-bot@example.org
          commit_author: Kedro Bot <actions@github.com>
          push_options: '--force'
          skip_dirty_check: true
          skip_fetch: false
          skip_checkout: false
          disable_globbing: true
          create_branch: false













